### ISSUE TITLE
Hire a Community Manager to help communication with IG/WG & Community

### ISSUE THREAD

**Issue by evvivaweinraub** [projecthydra-labs/power-steering#83] opened 2016-04-15 19:38 UTC
A number of the recommendations regarding IG/WG's would benefit from having an owner, e.g., writing up periodic update digests, making sure IG/WG calls are on the calendar, and more. It would be good to explore using Hydra $ to fund a community manager for some of these, until/unless a volunteer within the community steps forward to take this on.

**Comment by richardGreen** [comment] 2016-04-16 08:33
Duplicate of 65.

**Comment by kestlund** [comment] 2016-04-22 09:55
Closing as Duplicate of #65. Adding cross-refs.

**Closed as completed by kestlund** 2016-04-22 09:55 UTC
Labels: duplicate, steering, 2016 HPS
